providers = ["php", "node"]

[phases.install]
commands = [
  "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader",
  "npm ci",
]

[phases.build]
commands = [
  "npm run build",
  "php artisan optimize",
]

[start]
command = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"