providers = ["php", "node"]

[phases.install]
commands = [
  "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader",
  "npm ci",
]

[phases.build]
commands = [
  "npm run build"
]

[start]
command = "set -e; php -S 0.0.0.0:$PORT -t public public/index.php & SERVER_PID=$!; php artisan optimize:clear || true; php artisan config:cache || true; if [ \"$SKIP_AUTO_MIGRATE\" != \"true\" ]; then RETRIES=${MIGRATE_RETRIES:-10}; SLEEP=${MIGRATE_SLEEP:-5}; i=1; while [ \"$i\" -le \"$RETRIES\" ]; do php artisan migrate --force && break || true; echo \"Migration attempt $i failed; retrying in $SLEEP seconds...\"; sleep \"$SLEEP\"; i=$((i+1)); done; fi; php artisan storage:link || true; wait \"$SERVER_PID\""