CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "example" ("id" integer primary key autoincrement not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "departments" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "departments_name_unique" on "departments" ("name");
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "role" varchar not null default 'user', "is_admin" tinyint(1) not null default '0', "department_id" integer not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, foreign key("department_id") references "departments"("id") on delete cascade);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "processes" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "requires_document" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "consolidated_requests" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "status" varchar not null default 'pending', "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "purchase_requests" ("id" integer primary key autoincrement not null, "pr_number" varchar not null, "name" varchar not null, "order_date" date not null, "status" varchar not null default 'ATP', "remarks" text, "funding" varchar, "user_id" integer not null, "department_id" integer not null, "consolidated_request_id" integer, "workflow_steps" text, "is_archived" tinyint(1) not null default '0', "archived_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("department_id") references "departments"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "documents" ("id" integer primary key autoincrement not null, "name" varchar not null, "file_path" varchar not null, "mime_type" varchar, "file_size" integer, "purchase_request_id" integer not null, "uploaded_by" integer not null, "is_approved" tinyint(1) not null default '0', "approved_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("purchase_request_id") references "purchase_requests"("id") on delete cascade, foreign key("uploaded_by") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "consolidates" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "status" varchar not null default 'pending', "user_id" integer not null, "pr_numbers" text, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "bids" ("id" integer primary key autoincrement not null, "vendor_name" varchar not null, "amount" numeric not null, "purchase_request_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("purchase_request_id") references "purchase_requests"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" integer primary key autoincrement not null, "action" varchar not null, "description" text, "user_id" integer not null, "auditable_type" varchar not null, "auditable_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE INDEX "audit_logs_auditable_type_auditable_id_index" on "audit_logs" ("auditable_type", "auditable_id");
CREATE TABLE IF NOT EXISTS "status_histories" ("id" integer primary key autoincrement not null, "status" varchar not null, "notes" text, "purchase_request_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("purchase_request_id") references "purchase_requests"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "notifications" ("id" integer primary key autoincrement not null, "type" varchar not null, "data" text not null, "read_at" datetime, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "consolidate_purchase_request" ("id" integer primary key autoincrement not null, "consolidate_id" integer not null, "purchase_request_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("consolidate_id") references "consolidates"("id") on delete cascade, foreign key("purchase_request_id") references "purchase_requests"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_reset_tokens_table',1);
INSERT INTO migrations VALUES(3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(4,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2024_06_08_000000_create_processes_table',1);
INSERT INTO migrations VALUES(6,'2025_04_11_005045_create_purchase_requests_table',1);
INSERT INTO migrations VALUES(7,'2025_04_12_153058_create_departments_table',1);
INSERT INTO migrations VALUES(8,'2025_04_12_153237_add_department_id_to_users_table',1);
INSERT INTO migrations VALUES(9,'2025_04_12_155502_add_department_id_to_purchase_requests_table',1);
INSERT INTO migrations VALUES(10,'2025_04_12_160000_create_consolidated_requests_table',1);
INSERT INTO migrations VALUES(11,'2025_04_12_161014_update_existing_purchase_requests_department',1);
INSERT INTO migrations VALUES(12,'2025_04_12_170000_create_documents_table',1);
INSERT INTO migrations VALUES(13,'2025_04_12_180000_create_audit_logs_table',1);
INSERT INTO migrations VALUES(14,'2025_05_02_142648_create_bids_table',1);
INSERT INTO migrations VALUES(15,'2025_05_02_144627_add_type_to_purchase_requests_table',1);
INSERT INTO migrations VALUES(16,'2025_05_05_053042_create_consolidates_table',1);
INSERT INTO migrations VALUES(17,'2025_05_05_063655_add_is_admin_to_users_table',1);
INSERT INTO migrations VALUES(18,'2025_05_05_072232_create_example_table',1);
INSERT INTO migrations VALUES(19,'2025_05_05_120005_add_pr_numbers_to_consolidates_table',1);
INSERT INTO migrations VALUES(20,'2025_05_05_123007_recreate_purchase_requests_table',1);
INSERT INTO migrations VALUES(21,'2025_05_05_123317_add_name_to_purchase_requests_table',1);
INSERT INTO migrations VALUES(22,'2025_05_05_123318_add_archive_columns',1);
INSERT INTO migrations VALUES(23,'2025_05_05_145307_add_order_date_to_purchase_requests_table',1);
INSERT INTO migrations VALUES(24,'2025_05_05_161142_add_funding_to_purchase_requests_table',1);
INSERT INTO migrations VALUES(25,'2025_05_05_194947_create_consolidate_purchase_request_table',1);
INSERT INTO migrations VALUES(26,'2025_06_05_135951_create_status_histories_table',1);
INSERT INTO migrations VALUES(27,'2025_06_06_100001_add_concurrency_control',1);
INSERT INTO migrations VALUES(28,'2025_06_06_100002_cleanup_documents_table',1);
INSERT INTO migrations VALUES(29,'2025_06_06_100003_enhance_workflow_tracking',1);
INSERT INTO migrations VALUES(30,'2025_06_06_100004_remove_user_id_from_documents',1);
INSERT INTO migrations VALUES(31,'2025_06_06_100005_enhance_status_history',1);
INSERT INTO migrations VALUES(32,'2025_06_06_100006_add_enabled_steps_to_purchase_requests',1);
INSERT INTO migrations VALUES(33,'2025_07_02_074024_add_uploaded_by_to_documents_table',1);
INSERT INTO migrations VALUES(34,'2025_07_02_074143_make_mime_type_nullable_in_documents_table',1);
INSERT INTO migrations VALUES(35,'2025_07_02_074356_make_file_size_nullable_in_documents_table',1);
INSERT INTO migrations VALUES(36,'2025_07_02_080024_add_requires_document_to_processes_table',1);
INSERT INTO migrations VALUES(37,'2025_07_05_150711_create_notifications_table',1);
INSERT INTO migrations VALUES(38,'2025_07_29_140341_add_additional_fields_to_purchase_requests_table',1);
INSERT INTO migrations VALUES(39,'2025_07_29_141842_remove_type_column_from_purchase_requests_table',1);
INSERT INTO migrations VALUES(40,'2025_07_29_152015_add_completion_fields_to_purchase_requests_table',1);
INSERT INTO migrations VALUES(41,'2025_07_31_231409_add_profile_fields_to_users_table',1);
INSERT INTO migrations VALUES(42,'2025_08_13_130449_add_approval_fields_to_documents_table',1);
INSERT INTO migrations VALUES(43,'2025_10_12_145309_add_foreign_key_to_purchase_requests_consolidated_request_id',1);
INSERT INTO migrations VALUES(44,'2025_10_12_150000_fresh_start_migration',1);
